### ISSUE TITLE
Allow for passing LoroMap as an alternative to LoroDoc

### ISSUE THREAD

**Issue by raymonddaikon** [loro-dev/loro-prosemirror#17]
Currently the implementation sets its' own Map on the root LoroDoc with `ROOT_DOC_KEY` but I have a deeply nested Tree structure where each node can have its' own editor attached. It would be nice to be able to pass the LoroMap we want the plugin to sync to.

**Comment by zxch3n** [comment]
Sounds great! In your case, they all come from the same LoroDoc, right?

**Comment by raymonddaikon** [comment]
This is actually not as trivial as I first thought. I've been trying to get this functionality working locally, but it's not as simple as replacing everything with a LoroMap, theres a lot of assumptions about events emitted only by the root doc instance that aren't emitted by the LoroMap subscription.

**Comment by zxch3n** [comment]
> theres a lot of assumptions about events emitted only by the root doc instance that aren't emitted by the LoroMap subscription.

For events, there are a few differences. But it should not be a lot. Can you show me some examples so that I can see whether I can fix them internally?

**Comment by raymonddaikon** [comment]
Of course! I've narrowed down the problem to, when a doc imports a snapshot from an external source (for example when receiving updates from a BroadcastChannel or Websocket), a child LoroMap subscription is not triggered. This is mainly happening in the `updateNodeOnLoroEvent` function [here](https://github.com/loro-dev/loro-prosemirror/blob/main/src/sync-plugin.ts) on line 148.  I believe this could be because getting Containers returns a new object everytime and snapshot imports cause all the references to be invalidated? Also the `clearChangedNodes` function found [here](https://github.com/loro-dev/loro-prosemirror/blob/main/src/lib.ts)  line 653 seems to be problematic as doc imports don't preserve events. Let me know if you need me to make a fork with an updated example and my fragment implementation to better see the issues.

**Comment by raymonddaikon** [comment]
I made a fork with all my changes as well as an updated storybook example that uses the fragment implementation as well as a simplified version of how I'm using an external BroadcastChannel. https://github.com/raymonddaikon/loro-prosemirror

**Comment by zxch3n** [comment]
Thanks! That's very helpful.

**Comment by raymonddaikon** [comment]
I solved this in https://github.com/loro-dev/loro-prosemirror/pull/20

**Comment by zxch3n** [comment]
Awesome!
